### ISSUE TITLE
65536 GitHub Comment Character Limit

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#19]
This run seemed to have failed on the transmission step at the very end because according to the logs it even generated the permits, but then failed to post back to the original repository issue comments. 

A GitHub comment size is max 65536 characters long. Since the conversation incentives were so long, perhaps it makes sense to truncate the permit comment's metadata (we use HTML comments to comment out an embedded JSON object) or to somehow compress it further. 

https://github.com/ubiquibot/comment-incentives/actions/runs/7896867759/job/21551519371

```

Error: HttpError: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}

```

**Comment by pavlovcik** [comment]
@rndquu would you mind handling this? Getting payouts to work is a top priority and this seems like there's many ways to go about handling this.

**Comment by gitcoindev** [comment]
I may be able to fix this today, will try to set up and reproduce on my forked repository.

**Comment by gitcoindev** [comment]
> you think you can have this one @gitcoindev ?

Hi @molecula451 I am a bit stuck on the setup on my fork, it seems it needs to be run from org and depends on other config repositories. I tried to run locally from my local .env but in the end it needs github actions. If you feel you can fix this one quickly with QA please go ahead. I will experiment on my setup anyway today but feel free to pick it up -)

**Comment by molecula451** [comment]
we're all debugging on this one, so that's what im asking i think we're all can come with a good solution

**Comment by gitcoindev** [comment]
Ah sure. I also see @pavlovcik has been experimenting in parallel. I hope we can get it fixed together somehow.

**Comment by pavlovcik** [comment]
I'm setting up jest to mock the incoming event object

**Comment by pavlovcik** [comment]
It is somewhat stable (I discovered a bug!) so I'm working on that here https://github.com/ubiquibot/comment-incentives/pull/21

**Comment by gitcoindev** [comment]
Btw. I am not sure if I can see in the 'matrix' correctly today after I spent quite some time looking at logs -) but for me the root cause seems to be that the comment that *is going to be inserted* is too large because of another error.

I see that relevance-scoring thrown
```
Failed to average samples {
  error: TypeError: Cannot read properties of undefined (reading 'map')
      at averageSamples (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/relevance-scoring.ts:170:8) 
```
and in turn it created a cascade of trace dumps from failed generate-erc20-permit-signature.ts . This in total is larger than 65536 and it fails to insert such huge comment.

**Comment by gitcoindev** [comment]
I also downloaded [json](https://api.github.com/repos/ubiquity/ubiquity-dollar/issues/830/comments ) and wrote a simple script that calculated comment body lengths:
```
36
706
6
660
5
51
49
6
660
79
1898
204
69
157
634
46
172
395
195
1261
1526
195
491
714
195
2377
194
16820
120
265
Sum: 30186
```
So as you can see even the sum of characters in all comments in this issue is less than 65536, which also is in favor of the theory that the new comment to be inserted is too large due to error traces.

**Comment by molecula451** [comment]
30186? then is almost half of the acceptable character limit

**Comment by pavlovcik** [comment]
> Btw. I am not sure if I can see in the 'matrix' correctly today after I spent quite some time looking at logs -) but for me the root cause seems to be that the comment that _is going to be inserted_ is too large because of another error.
> 
> I see that relevance-scoring thrown
> 
> ```
> Failed to average samples {
>   error: TypeError: Cannot read properties of undefined (reading 'map')
>       at averageSamples (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/relevance-scoring.ts:170:8) 
> ```
> 
> and in turn it created a cascade of trace dumps from failed generate-erc20-permit-signature.ts . This in total is larger than 65536 and it fails to insert such huge comment.

Yea the bug I identified was that I accidentally coded it to check if the price labels ARRAY exists, instead of checking that the length is zero. That seemed to throw that map error that I would see so commonly in the logs. 

In this specific scenario, the issue has no labels and I think the code was not designed to handle that. Still getting it stable, I'm at permit generation part now (missing private key in my env vars!)

https://github.com/ubiquibot/comment-incentives/blob/77ba9b0fc95924930eaeaa3cbfe689bef26ab4f8/src/handlers/issue/assignee-scoring.ts#L6-L75

**Comment by pavlovcik** [comment]
This is a pretty solid co-op campaign

**Comment by pavlovcik** [comment]
Hey guys, I got it to work! Can somebody work on generating a new `X25519_PRIVATE_KEY` for the ubiquibot organization? We need to share it for development purposes.

1. Generate a new key
2. Encrypt a new `evmPrivateKeyEncrypted` (no funds!)
3. Add the shared test key to the `comment-incentives` readme. 

https://github.com/ubiquibot/comment-incentives/pull/21/commits/567419d9688e92edf698f64c697f1a7cafe1d02e

**Comment by pavlovcik** [comment]
> ```diff
> + Evaluating results. Please wait...
> ```

Looks like it happened again. I'll use this exact issue to test and push another fix asap!

**Comment by molecula451** [comment]
btw judging the gitcoindev message i think the character set it's manipulatible say if i post a comment that long loooking like a drop down table the bot could think that perhaps my contribution comment is that helpful because of longer?

need to round well

**Comment by molecula451** [comment]
indeed it happened 

![image_2024-02-16_132738180](https://github.com/ubiquibot/comment-incentives/assets/41552663/631c160b-1fcf-4e8a-bff4-481243581567)

**Comment by pavlovcik** [comment]
Here is the full transmission for the broken comment:

[1708104501473.html.zip](https://github.com/ubiquibot/comment-incentives/files/14314104/1708104501473.html.zip)
