### ISSUE TITLE
`TypeError: counter.plus is not a function`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#31]
There's an issue I've never seen before. Please research a solution before we fund this issue. 

```
TypeError: counter.plus is not a function
    at CommentScoring._calculateWordScores (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/comment-scoring-rubric.ts:164:25)
    at CommentScoring.computeWordScore (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/comment-scoring-rubric.ts:255:35)
    at perUserCommentScoring (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/per-user-comment-scoring.ts:10:19)
    at <anonymous> (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/all-comment-scoring.ts:43:9)
    at Array.forEach (<anonymous>)
    at <anonymous> (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/all-comment-scoring.ts:39:13)
    at Array.flatMap (<anonymous>)
    at allCommentScoring (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/all-comment-scoring.ts:25:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at commentsScoring (/home/runner/work/comment-incentives/comment-incentives/src/handlers/issue/evaluate-comments.ts:28:40)
Error: TypeError: counter.plus is not a function
```

Source https://github.com/ubiquibot/comment-incentives/actions/runs/8002349026/job/21855360540#step:5:262
Related https://github.com/ubiquity/nft-rewards/issues/3#issuecomment-1959049060

**Comment by molecula451** [comment]
relates to the [decimal.js](https://www.npmjs.com/package/decimal.js/v/10.0.2) package

**Comment by Keyrxng** [comment]
It looks like it's failing for the word constructor as far as I can tell

![image](https://github.com/ubiquibot/comment-incentives/assets/106303466/ca17566a-21f9-4df6-840a-389a57ed77df)


```bash
==== error ====
word:  constructor
==== 5 before ====
[ 'function', 'was', 'async', 'but', 'the' ]
==== 5 after ====
[ 'constructor', 'isn', 't', 'I', 'was' ]
```

**Comment by Keyrxng** [comment]
``_getWordsNotInDisabledElements()`` seems like the only sort of 'blacklist' but it's for elements as opposed to literal strings, have I missed in it the codebase or is there a need to add something like it for literals?

**Comment by molecula451** [comment]
working https://github.com/ubiquibot/comment-incentives/actions/runs/8288619639, nice hack! @Keyrxng

**Comment by Keyrxng** [comment]
I'm full of them 😂
